// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgpfgbdoygwzltgrteqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNncGZnYmRveWd3emx0Z3J0ZXFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMjM2NTUsImV4cCI6MjA2ODc5OTY1NX0.DAda7VLKgr6G2ZT8FMWZ8XXVTHS3oYyGaXqntH8BkdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});